[package]
name = "cpu-meter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.30"
serialport = "4.3"
tray-item = "0.10"

[build-dependencies]
embed-resource = "2.3"
